target 'CFOnlineShop' do
platform:ios,'9.0'

pod 'MJExtension', '~> 3.0.10'
pod 'SDCycleScrollView','~> 1.75'
pod 'RollingNotice'
pod 'AFNetworking', '~> 3.2.1'
pod 'MJExtension', '~> 3.0.13'
pod 'DZNEmptyDataSet', '~> 1.8.1'
pod 'WechatOpenSDK'

end
